import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms and Conditions | Beond",
  description: "Terms and conditions of Beond's website.",
};

export default function TermsAndConditionsPage() {
  return (
    <main className="bg-(--color-surface-2) text-(--color-foreground)">
      <div className="site-container py-12 md:py-16">
        <nav aria-label="Breadcrumb" className="text-xs text-(--color-muted)">
          <ol className="flex flex-wrap items-center gap-2 p-0 m-0 list-none">
            <li>
              <Link href="/" className="hover:underline underline-offset-4">
                Home
              </Link>
            </li>
            <li aria-hidden className="text-black/25">
              /
            </li>
            <li className="text-(--color-foreground)">Terms and Conditions</li>
          </ol>
        </nav>

        <h1 className="mt-4 text-3xl font-semibold tracking-tight md:text-4xl lg:text-5xl">
          Terms and Conditions
        </h1>
        <p className="mt-4 max-w-4xl text-sm leading-relaxed text-(--color-muted) md:text-base">
          These are the terms of use for all websites operated by us, Beond Simdi
          Operations Pvt. Ltd, BeOnd Aivation DWC LLC (trading as “Be0nd”)
          especially{" "}
          <a
            className="font-semibold text-(--color-foreground) hover:underline underline-offset-4"
            href="https://flybeond.com/"
            target="_blank"
            rel="noopener noreferrer"
          >
            flybeond.com
          </a>{" "}
          (hereinafter collectively referred to as &quot;Website&quot;).
        </p>

        <div className="mt-10 max-w-4xl space-y-10">
          <section>
            <h2 className="text-xl font-semibold md:text-2xl">1. General</h2>
            <p className="mt-3 text-sm leading-relaxed text-(--color-muted) md:text-base">
              The Website is operated by Be0nd and additional terms and
              conditions apply to contracts concluded via the Website.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold md:text-2xl">
              2. Copyrights trademarks and other intellectual property rights
            </h2>
            <p className="mt-3 text-sm leading-relaxed text-(--color-muted) md:text-base">
              Be0nd or its licensors own all trademark rights, copyrights,
              database rights and other intellectual property rights in the
              content of the Website, together with the underlying software
              code. You may not copy, modify, distribute or otherwise use or
              reproduce in any way, in whole or in part, any content of the
              Website or the underlying software code without the prior written
              permission of Be0nd.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold md:text-2xl">
              3. Use of the Website
            </h2>
            <p className="mt-3 text-sm leading-relaxed text-(--color-muted) md:text-base">
              All online services (including the booking engine) of the Website
              are provided solely for the purpose of enabling you to check the
              availability of travel-related goods or services (for example, the
              flight schedule), to make legitimate reservations, to use our
              online check-in or to conduct other business with suppliers. You
              may use the Website only in accordance with these Terms of Use and
              for the lawful purposes described above. In particular, you agree
              to the following:
            </p>
            <ul className="mt-4 list-disc space-y-2 pl-5 text-sm leading-relaxed text-(--color-muted) md:text-base">
              <li>
                You may not use the Website in any manner that is likely to
                infringe the proprietary rights of others.
              </li>
              <li>
                You may not use any devices, mechanisms, software or other
                scripts that may interfere with the operation of the Website.
                This also includes loading files infected with viruses.
              </li>
              <li>
                You may not take any action that could result in an unreasonable
                or excessive load on our IT infrastructure.
              </li>
              <li>
                You may not block, overwrite or modify any content generated by
                us or interfere with the Website in any other way.
              </li>
              <li>
                You may not reproduce data from the Website for commercial
                purposes. This includes quoting prices for our flights on
                another website or online server. In particular, you may not
                copy, distribute, otherwise use or reproduce the content stored
                on the Website by means of the use of &quot;robots&quot;, other
                search engine technologies or by other automatic mechanisms.
              </li>
              <li>
                You may not make any unauthorized, false or fraudulent bookings,
                including but not limited to bookings paid for by credit card or
                under account of a third party who has not consented to this.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold md:text-2xl">
              4. Consequences of unauthorized use
            </h2>
            <p className="mt-3 text-sm leading-relaxed text-(--color-muted) md:text-base">
              Without prejudice to our other rights (whether based on law or
              otherwise), we reserve the right to cancel your bookings without
              notice to you and/or to prohibit you from accessing the Website if
              you have breached these Terms of Use.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold md:text-2xl">
              5. Changes to the Website
            </h2>
            <p className="mt-3 text-sm leading-relaxed text-(--color-muted) md:text-base">
              We reserve the right to make improvements or changes to the
              information, services, products and other content of the Website
              at any time without notice. The same applies to these Terms of
              Use.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold md:text-2xl">
              6. Links to other websites
            </h2>
            <p className="mt-3 text-sm leading-relaxed text-(--color-muted) md:text-base">
              This website may contain links or references to other websites
              that are not operated by us. Unless otherwise stated, we do not
              endorse any of these other websites and hereby expressly distance
              ourselves from all content on such sites.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold md:text-2xl">7. Disclaimer</h2>
            <p className="mt-3 text-sm leading-relaxed text-(--color-muted) md:text-base">
              The Website represents a non-binding offer of information. The
              information may change at any time. Be0nd assumes no liability for
              the topicality, correctness, completeness or quality of the
              information provided by third parties (e.g. cooperation partners,
              tour operators, airports, etc.).
            </p>
            <p className="mt-6 text-sm font-semibold text-(--color-foreground)">
              August 2023
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}

